### ISSUE TITLE
Rename npm package to sketchfab

### ISSUE THREAD

**Issue by samt** [sketchfab/node-sketchfab#2]
Most people tend to try find names like `NAME` more memorable (not to mention 'official') than `node-NAME` because it seems to suggest that there are different ways a library has been done, i.e. `node- NAME`, `NAME-node`, `NAME-js`, etc.

This would be a pretty simple and non-breaking change as you could then publish a new package under the name`node-sketchfab` with a single file that just includes the new one but not before outputting a deprecation notice. :smiley:

**Comment by mauricesvay** [comment]
Sounds like a good idea

**Comment by pierreant-p** [comment]
Done. Let us know how it goes.
